name: onedayclan

on:
  workflow_dispatch

env:
  RESOURCE_PATH: /src/main/resources/application.yml
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      
      - name: Set yaml file
        uses: microsoft/variable-substitution@v1
        with:
          files: ${{ env.RESOURCE_PATH }}
        env:
          spring.datasource.url: jdbc.mysql://${{ secrets.DATASOURCE_HOST }}:${{ secrets.DATASOURCE_PORT }}/${{ secrets.DATASOURCE_DATABASE }}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
          spring.datasource.username: ${{ secrets.DATASOURCE_USERNAME }}
          spring.datasource.password: ${{ secrets.DATASOURCE_PASSWORD }}
          spring.mail.username: ${{ secrets.MAIL_USERNAME }}
          spring.mail.password: ${{ secrets.MAIL_PASSWORD }}
          navercloud.sms.service-id: ${{ secrets.SMS_SERVICE_ID}}
          navercloud.sms.secret-key: ${{ secrets.SMS_SECRET_KEY }}
          navercloud.sms.access-key: ${{ secrets.SMS_ACCESS_KEY }}
          navercloud.sms.from: ${{ secrets.SMS_FROM }}
          jwt.secret: ${{ secrets.JWT_SECRET }}
      
      - name: Build with Maven
        run : mvn -B package --file pom.xml
        
      
        
